/**
 * 
 */
package com.sarvah.mbg.domain.mongo.userprofile;

/**
 * @author shivu s
 *
 */
public enum ServiceProviders {

	ARCHITECT, INTERIORDESIGNER, PLUMBER, PAINTER, CARPENTER, CIVILENGINEER, VASTHUCONSULTANTS, ELECTRICIANS, BIMCONSULTANTS, PROJECTCONSULTANT, LANDSCAPEARCHITECT, SURVEYOR, WATERDIVINER, VALUATOR, BOREWELL, FLOORINGCONTRACTOR, FABRICATOR, CIVILCONTRACTOR, GEOLOGIST, ELECTRICALCONSULTANT;

}
